services:
  key2pfx:
    container_name: key2pfx-dev
    # entrypoint: ["/bin/bash", "-c"]
    # command: ["sleep infinity"]
    image: key2pfx:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        ALPINE_VERSION: 3.21.3
        OPENSSL_VERSION: 3.3.3-r0
    environment:
      - CRT=/certs/tls.crt
      - KEY=/certs/tls.key
      - CA=/certs/ca.crt
      - OUT=/output/cert-custom.pfx
      - PASSWORD=enjoyworking
    volumes:
      - ./mock-certs:/certs
      - ./ouput:/output